debug report

diff --git a/.github/workflows/tamahouseTest.yml b/.github/workflows/tamahouseTest.yml
--- a/.github/workflows/tamahouseTest.yml
+++ b/.github/workflows/tamahouseTest.yml
@@ -128,6 +128,19 @@ jobs:
       - name: Run Test
         working-directory: automation
         run: mvn clean test -Pregression -Devn=staging -Dbrowser=${{ matrix.browser }} -DbaseUrl=https://chaseqa.duckdns.org -DremoteUrl=http://localhost:4444
+        
+      - name: Check allure results exist
+        run: |
+            if [ ! -d "automation/target/allure-results" ]; then
+            echo "No allure results → skip SCP"
+            exit 0
+            fi
+            echo "📂 List files:"
+            ls -la automation/target/allure-results
+            if [ -z "$(ls -A automation/target/allure-results)" ]; then
+            echo "❌ Folder rỗng → skip SCP"
+            exit 0
+            fi
 
       - name: Prepare folders on VPS
         if: always()
@@ -151,6 +164,16 @@ jobs:
           source: "automation/target/allure-results/*"
           target: "allure-results/${{ needs.build-deploy.outputs.TEMP_TAG }}/${{ matrix.browser }}"
           strip_components: 3 
+          
+      - name: Verify on VPS
+        uses: appleboy/ssh-action@v1.0.3
+        with:
+            host: ${{ secrets.VPS_HOST }}
+            username: ${{ secrets.VPS_USER }}
+            key: ${{ secrets.VPS_SSH_KEY }}
+            script: |
+                ls -la allure-results
+                ls -la allure-results/${{ needs.build-deploy.outputs.TEMP_TAG }} || echo "NOT FOUND"
 
       - name: Stop Selenium
         if: always()
