update yml 19

diff --git a/.github/workflows/tamahouseTest.yml b/.github/workflows/tamahouseTest.yml
--- a/.github/workflows/tamahouseTest.yml
+++ b/.github/workflows/tamahouseTest.yml
@@ -75,6 +75,13 @@ jobs:
                 path: automation
                 token: ${{secrets.GITHUB_TOKEN}}
                 
+            - name: Verify automation repo
+              run: |
+                echo "=== ROOT ==="
+                ls -la
+                echo "=== AUTOMATION ==="
+                ls -la automation || echo "❌ automation NOT FOUND"
+                
             - name: Start Selenium
               run: sudo docker run -d -p 4444:4444 --name selenium selenium/standalone-${{ matrix.browser }}
                 
